/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package rindirect.r1;

public final class R {
    public static final class array {

        public static final int enumDidYouKnow=0x7f050004;
        public static final int enumSettingsAppearanceFontSize=0x7f050000;
        public static final int enumSettingsAppearanceFontSizeHumanReadable=0x7f050002;
        public static final int enumSettingsAppearanceScreenRotation=0x7f050001;
        public static final int enumSettingsAppearanceScreenRotationHumanReadable=0x7f050003;

        public static final int enumSettingsBillingAddressCountriesHumanReadable=0x7f050005;
    }
    public static final class attr {

        public static final int verified=0x7f010000;

        public static final int verifiedText=0x7f010001;
    }
    public static final class color {
        public static final int background=0x7f070000;
        public static final int divider=0x7f070004;
        public static final int foreground=0x7f070001;
        public static final int preferenceCategoryBackground=0x7f070003;
        public static final int preferenceCategoryForeground=0x7f070002;
        /**  color names
         */
        public static final int translucid_blue=0x7f070006;
        public static final int verifiedGreen=0x7f070005;
    }
    public static final class drawable {
        public static final int a_minus=0x7f020000;
        public static final int a_plus=0x7f020001;
        public static final int add=0x7f020002;
        public static final int archive=0x7f020003;
        public static final int asmall_abig=0x7f020004;
        public static final int collection=0x7f020005;
        public static final int delete=0x7f020006;
        public static final int document_placeholder=0x7f020007;
        public static final int document_placeholder_big=0x7f020008;
        public static final int featured=0x7f020009;
        public static final int folder=0x7f02000a;
        public static final int green_checkmark=0x7f02000b;
        public static final int home_txtr=0x7f02000c;
        public static final int icon=0x7f02000d;
        public static final int inbox=0x7f02000e;
        public static final int intro=0x7f02000f;
        public static final int launcher_48px=0x7f020010;
        public static final int logo=0x7f020011;
        public static final int menu_appearance=0x7f020012;
        public static final int menu_book_info=0x7f020013;
        public static final int menu_bookmark=0x7f020014;
        public static final int menu_home=0x7f020015;
        public static final int menu_navigate=0x7f020016;
        public static final int menu_settings=0x7f020017;
        public static final int menu_sort=0x7f020018;
        public static final int menu_upload=0x7f020019;
        public static final int my_account=0x7f02001a;
        public static final int night_mode=0x7f02001b;
        public static final int old_archive_non_selected=0x7f02001c;
        public static final int old_archive_selected=0x7f02001d;
        public static final int old_bookmark=0x7f02001e;
        public static final int old_document_placeholder=0x7f02001f;
        public static final int old_featured_non_selected=0x7f020020;
        public static final int old_featured_selected=0x7f020021;
        public static final int old_green_checkmark=0x7f020022;
        public static final int old_home=0x7f020023;
        public static final int old_home1=0x7f020024;
        public static final int old_intro=0x7f020025;
        public static final int old_launcher_48px=0x7f020026;
        public static final int old_recent_non_selected=0x7f020027;
        public static final int old_recent_selected=0x7f020028;
        public static final int old_settings=0x7f020029;
        public static final int old_settings1=0x7f02002a;
        public static final int old_store_non_selected=0x7f02002b;
        public static final int old_store_selected=0x7f02002c;
        public static final int old_upload=0x7f02002d;
        public static final int old_upload_pictogram=0x7f02002e;
        public static final int read=0x7f02002f;
        public static final int recent=0x7f020030;
        public static final int remote_collection=0x7f020031;
        public static final int search=0x7f020032;
        public static final int status_bar_icon=0x7f020033;
        public static final int store=0x7f020034;
        public static final int tabs_archive_non_selected=0x7f020035;
        public static final int tabs_archive_selected=0x7f020036;
        public static final int tabs_featured_non_selected=0x7f020037;
        public static final int tabs_featured_selected=0x7f020038;
        public static final int tabs_recent_non_selected=0x7f020039;
        public static final int tabs_recent_selected=0x7f02003a;
        public static final int tabs_store_non_selected=0x7f02003b;
        public static final int tabs_store_selected=0x7f02003c;
        public static final int trash=0x7f02003d;
        public static final int txtr_doc_big=0x7f02003e;
        public static final int txtr_logo_quote_60=0x7f02003f;
        public static final int txtr_logo_quote_60_white=0x7f020040;
    }
    public static final class id {
        public static final int BookmarkAdd=0x7f0a000c;
        public static final int BookmarkCancel=0x7f0a000d;
        public static final int BookmarkName=0x7f0a000b;
        public static final int aboutWebView=0x7f0a0002;
        public static final int adobeId=0x7f0a0003;
        public static final int adobePassword=0x7f0a0004;
        public static final int buttonAgree=0x7f0a0046;
        public static final int buttonCancel=0x7f0a0041;
        public static final int buttonCheckout=0x7f0a000a;
        public static final int buttonCreateAdobeAccount=0x7f0a0039;
        public static final int buttonDisagree=0x7f0a0047;
        public static final int buttonDocumentInfo=0x7f0a0018;
        public static final int buttonSubmit=0x7f0a0038;
        public static final int buttonUpload=0x7f0a004d;
        public static final int checkoutDocumentAuthor=0x7f0a0009;
        public static final int checkoutDocumentAuthorRow=0x7f0a0008;
        public static final int checkoutDocumentCover=0x7f0a0006;
        public static final int checkoutDocumentTitle=0x7f0a0007;
        public static final int custom_notificationbar=0x7f0a0048;
        public static final int documentAuthor=0x7f0a0025;
        public static final int documentAuthorLine=0x7f0a0024;
        public static final int documentInfoAuthor=0x7f0a0017;
        public static final int documentInfoAuthorRow=0x7f0a0016;
        public static final int documentInfoCover=0x7f0a0014;
        public static final int documentInfoDescription=0x7f0a0021;
        public static final int documentInfoDescriptionParent=0x7f0a0020;
        public static final int documentInfoFormat=0x7f0a001f;
        public static final int documentInfoFormatRow=0x7f0a001e;
        public static final int documentInfoPublishedDate=0x7f0a001b;
        public static final int documentInfoPublishedDateRow=0x7f0a001a;
        public static final int documentInfoPublisher=0x7f0a001d;
        public static final int documentInfoPublisherRow=0x7f0a001c;
        public static final int documentInfoRoot=0x7f0a0013;
        public static final int documentInfoTitle=0x7f0a0015;
        public static final int documentStatus=0x7f0a0027;
        public static final int documentStatusLine=0x7f0a0026;
        public static final int documentThumbnail=0x7f0a0022;
        public static final int documentTitle=0x7f0a0023;
        public static final int dynButtonClose=0x7f0a000e;
        public static final int dynButtonNext=0x7f0a0011;
        public static final int dynButtonPrevious=0x7f0a0010;
        public static final int dynCheckboxDoNotShowAgain=0x7f0a0012;
        public static final int dynText=0x7f0a000f;
        public static final int emptyListImage=0x7f0a002f;
        public static final int goto_button=0x7f0a002c;
        public static final int goto_entry=0x7f0a0029;
        public static final int goto_layout=0x7f0a0028;
        public static final int goto_progress=0x7f0a002a;
        public static final int goto_slider=0x7f0a002b;
        public static final int introImage=0x7f0a002d;
        public static final int listEmptyTitle=0x7f0a0030;
        public static final int listRoot=0x7f0a002e;
        public static final int menuGroupAlways=0x7f0a004e;
        public static final int menuGroupSortable=0x7f0a0051;
        public static final int menuItemSearch=0x7f0a004f;
        public static final int menuItemSettings=0x7f0a0050;
        public static final int menuItemSort=0x7f0a0052;
        public static final int notify_image=0x7f0a0049;
        public static final int notify_progressbar=0x7f0a004b;
        public static final int notify_progressbar_container=0x7f0a004a;
        public static final int notify_text=0x7f0a004c;
        public static final int progressBarDocumentInfo=0x7f0a0019;
        public static final int renderer_content=0x7f0a0033;
        public static final int renderer_scroll=0x7f0a0035;
        public static final int rootView=0x7f0a0005;
        public static final int settingsAdobeAccountEditPassword=0x7f0a0037;
        public static final int settingsAdobeAccountEditUsername=0x7f0a0036;
        public static final int settingsBillingAddressEditCity=0x7f0a003f;
        public static final int settingsBillingAddressEditFirstName=0x7f0a003a;
        public static final int settingsBillingAddressEditLastName=0x7f0a003b;
        public static final int settingsBillingAddressEditPart1=0x7f0a003c;
        public static final int settingsBillingAddressEditPart2=0x7f0a003d;
        public static final int settingsBillingAddressEditZipcode=0x7f0a003e;
        public static final int settingsBillingAddressSpinnerCountries=0x7f0a0040;
        public static final int settingsRoot=0x7f0a0000;
        public static final int settingsUserAccountEditEmail=0x7f0a0043;
        public static final int settingsUserAccountEditPassword=0x7f0a0044;
        public static final int settingsUserAccountEditPasswordRetype=0x7f0a0045;
        public static final int settingsUserAccountEditUsername=0x7f0a0042;
        public static final int titleImage=0x7f0a0001;
        public static final int viewFlipper=0x7f0a0032;
        public static final int web=0x7f0a0031;
        public static final int webView=0x7f0a0034;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int adobe_password=0x7f030001;
        public static final int checkout=0x7f030002;
        public static final int create_bookmark_dialog=0x7f030003;
        public static final int dialog_didyouknow=0x7f030004;
        public static final int document_information=0x7f030005;
        public static final int document_listentry=0x7f030006;
        public static final int document_loadingentry=0x7f030007;
        public static final int epub_overlay=0x7f030008;
        public static final int goto_dialog=0x7f030009;
        public static final int intro=0x7f03000a;
        public static final int list=0x7f03000b;
        public static final int not_authenticated=0x7f03000c;
        public static final int not_connected=0x7f03000d;
        public static final int payment_form=0x7f03000e;
        public static final int renderer_epub=0x7f03000f;
        public static final int renderer_html=0x7f030010;
        public static final int renderer_pdf=0x7f030011;
        public static final int renderer_txt=0x7f030012;
        public static final int settings=0x7f030013;
        public static final int settings_adobe_login=0x7f030014;
        public static final int settings_billing_address=0x7f030015;
        public static final int settings_createaccount=0x7f030016;
        public static final int settings_login=0x7f030017;
        public static final int settings_terms_conditions=0x7f030018;
        public static final int tabs=0x7f030019;
        public static final int transfer_notification=0x7f03001a;
        public static final int upload=0x7f03001b;
    }
    public static final class menu {
        public static final int menu_main=0x7f090000;
    }
    public static final class string {
        public static final int about=0x7f0600c8;
        public static final int accepted=0x7f06009d;
        public static final int add_document_to_inbox=0x7f060002;
        public static final int addressPart1=0x7f0600a2;
        public static final int addressPart2=0x7f0600a3;
        public static final int adobeCreateAccountUrl=0x7f0600c9;
        public static final int adobeDrmDescription=0x7f06004d;
        public static final int adobeDrmSubDescription=0x7f06004e;
        public static final int adobeMoreAboutDrm=0x7f06004c;
        public static final int adobePassword=0x7f06004f;
        public static final int app_copyright=0x7f0600c5;
        public static final int app_name=0x7f0600c4;
        public static final int app_subtitle=0x7f0600c6;
        public static final int author=0x7f060099;
        public static final int bookmark_title=0x7f060025;
        public static final int buttonLabelActivate=0x7f060030;
        public static final int buttonLabelAgree=0x7f060034;
        public static final int buttonLabelBuyNowFor=0x7f060064;
        public static final int buttonLabelCancel=0x7f06002c;
        public static final int buttonLabelChange=0x7f060032;
        public static final int buttonLabelCheck=0x7f060031;
        public static final int buttonLabelClose=0x7f060036;
        public static final int buttonLabelContinueReading=0x7f060038;
        public static final int buttonLabelCreate=0x7f06002f;
        public static final int buttonLabelCreateAdobeAccount=0x7f060047;
        public static final int buttonLabelDisagree=0x7f060035;
        public static final int buttonLabelDownload=0x7f06008c;
        /**  EN
 DE
         */
        public static final int buttonLabelOk=0x7f06002b;
        public static final int buttonLabelReset=0x7f060033;
        public static final int buttonLabelSearch=0x7f060077;
        public static final int buttonLabelSignIn=0x7f06002e;
        public static final int buttonLabelStartReading=0x7f060037;
        public static final int buttonLabelSubmit=0x7f06002d;

        public static final int buttonLabelSubmitAdobeId=0x7f060046;
        public static final int buttonLabelUpload=0x7f06008d;
        public static final int by=0x7f06009c;
        public static final int city=0x7f0600a5;
        public static final int colorMode=0x7f0600a6;

        public static final int connector_adapter=0x7f0600c0;

        public static final int connector_description=0x7f0600bf;

        public static final int contextMenuItemLabelDelete=0x7f06006e;
        public static final int contextMenuItemLabelInfo=0x7f06006f;
        public static final int createBookmark=0x7f060026;
        public static final int date=0x7f06009a;
        public static final int document=0x7f060097;
        public static final int documentAbout=0x7f060045;
        public static final int documentFormat=0x7f060042;
        public static final int documentPublishedDate=0x7f060043;
        public static final int documentPublisher=0x7f060044;
        public static final int email=0x7f060094;
        public static final int enumSettingsAppearanceFontSizeDefault=0x7f060000;
        public static final int enumSettingsAppearanceScreenRotationDefault=0x7f060001;
        public static final int firstName=0x7f0600a0;
        public static final int fontSize=0x7f0600a7;
        public static final int idSettingsBillingAddress=0x7f0600ae;
        public static final int idSettingsDrmDeactivateDevice=0x7f0600b3;
        public static final int idSettingsDrmLogin=0x7f0600b2;
        public static final int idSettingsLogout=0x7f0600b1;
        public static final int idSettingsMoreAbout=0x7f0600b4;
        public static final int idSettingsMoreFeedback=0x7f0600b5;
        public static final int idSettingsPaymentMethod=0x7f0600af;
        public static final int idSettingsTermsConditions=0x7f0600b0;
        public static final int idSettingsUserAccountCreate=0x7f0600ad;

        public static final int idSettingsUserAccountLogin=0x7f0600ac;
        public static final int keyNextHintToShow=0x7f0600bc;
        public static final int keyProvisioningDone=0x7f0600bb;

        public static final int keySettingsAppearanceFontSize=0x7f0600b6;
        public static final int keySettingsAppearanceNightMode=0x7f0600b8;
        public static final int keySettingsAppearanceScreenRotation=0x7f0600b7;
        public static final int keySettingsMoreShowHintsOnStartup=0x7f0600b9;
        public static final int keySettingsMoreUseSdCard=0x7f0600ba;
        public static final int labelDoNotShowAgain=0x7f06003e;
        public static final int lastName=0x7f0600a1;
        public static final int library_version=0x7f0600c7;

        public static final int menuItemAppearance=0x7f060018;
        public static final int menuItemSearch=0x7f060075;
        public static final int menuItemSettings=0x7f06007a;

        public static final int menuItemSort=0x7f060081;
        public static final int menuItemSortByLatestRead=0x7f060084;
        public static final int menuItemSortByRecentlyDownloaded=0x7f060083;
        public static final int menuItemSortByTitle=0x7f060082;
        public static final int menuItemUpload=0x7f06008b;
        public static final int messageAboutToUploadInfo=0x7f060091;
        public static final int messageAccountCreationFailed=0x7f060016;
        public static final int messageActivatingDevice=0x7f060055;
        public static final int messageAdobeIdEmpty=0x7f060050;
        public static final int messageCannotReadDocument=0x7f060071;
        public static final int messageCannotReadDrm=0x7f060051;
        public static final int messageCheckoutFailed=0x7f06006c;
        public static final int messageCheckoutSucceeded=0x7f06006d;
        public static final int messageConfirmDeviceDeactivation=0x7f060056;
        public static final int messageDeviceNotActivated=0x7f060052;
        public static final int messageDidYouKnow=0x7f060040;
        public static final int messageDocumentContentReadFailure=0x7f060072;
        public static final int messageEmailEmpty=0x7f06000d;
        public static final int messageEnterAdobePassword=0x7f060057;
        public static final int messageErrorWhileSorting=0x7f060085;
        public static final int messageInternalError=0x7f06005a;
        public static final int messageInvalidCaptcha=0x7f060013;
        public static final int messageLoading=0x7f060059;
        public static final int messageLoggingOut=0x7f06000a;
        public static final int messageLoginFailed=0x7f060017;

        public static final int messageNeedInternet=0x7f060039;
        public static final int messageNoBookmarks=0x7f060027;
        public static final int messageNoToc=0x7f060061;
        public static final int messagePasswordEmpty=0x7f06000c;
        public static final int messagePasswordInvalid=0x7f060014;
        public static final int messagePasswordsDontMatch=0x7f060015;
        public static final int messagePaymentDataAlreadySet=0x7f06006b;
        public static final int messagePaymentMethodRefused=0x7f060069;
        public static final int messagePaymentMethodSuccessfullySet=0x7f06006a;

        public static final int messagePleaseCheckYourInput=0x7f060058;
        public static final int messageReadError=0x7f06005b;
        public static final int messageSearchRequiresConnectivity=0x7f060078;
        public static final int messageTransferCancelled=0x7f060090;
        public static final int messageTransferCompleted=0x7f06008f;
        public static final int messageTransferring=0x7f06008e;
        public static final int messageUnableToActivateDevice=0x7f060053;
        public static final int messageUnableToContactServer=0x7f06003a;
        public static final int messageUnableToDeactivateDevice=0x7f060054;
        public static final int messageUnableToDisplayAsset=0x7f06002a;
        public static final int messageUnableToFetchDocuments=0x7f06003b;
        public static final int messageUnableToFetchMoreDocuments=0x7f06003c;
        public static final int messageUnsupportedFileType=0x7f06003d;
        public static final int messageUsernameContainsInvalidChars=0x7f060010;
        public static final int messageUsernameEmpty=0x7f06000b;
        public static final int messageUsernameInUse=0x7f060012;
        public static final int messageUsernameStartsWithInvalidChar=0x7f060011;
        public static final int messageUsernameTooLong=0x7f06000f;
        public static final int messageUsernameTooShort=0x7f06000e;
        public static final int next=0x7f0600aa;

        public static final int noDocuments=0x7f060041;
        public static final int page=0x7f0600a8;
        public static final int pageTitleArchive=0x7f060087;
        public static final int pageTitleCheckout=0x7f060063;
        public static final int pageTitleFeatured=0x7f060088;
        public static final int pageTitleHome=0x7f060073;

        public static final int pageTitleRecent=0x7f060086;

        public static final int pageTitleSearch=0x7f060074;

        public static final int pageTitleSettings=0x7f060079;
        public static final int pageTitleStore=0x7f060089;

        public static final int pageTitleUpload=0x7f06008a;
        public static final int password=0x7f060095;
        public static final int passwordRetype=0x7f060096;
        public static final int payment_endpoint=0x7f0600be;
        public static final int preferenceAbout=0x7f06007d;
        public static final int preferenceAboutSummary=0x7f06007e;
        public static final int preferenceAdobe=0x7f060048;
        public static final int preferenceAdobeLogin=0x7f060049;
        public static final int preferenceAdobeLoginSummary=0x7f06004a;
        public static final int preferenceAppearance=0x7f060019;
        public static final int preferenceBillingAddress=0x7f060065;
        public static final int preferenceBillingAddressSummary=0x7f060066;
        public static final int preferenceColorMode=0x7f06001c;
        public static final int preferenceColorModeMonochrome=0x7f06001e;
        public static final int preferenceColorModeNormal=0x7f06001d;
        public static final int preferenceDeactivateDevice=0x7f06004b;
        public static final int preferenceFeedback=0x7f06007f;
        public static final int preferenceFeedbackSummary=0x7f060080;
        public static final int preferenceFontSize=0x7f06001a;
        public static final int preferenceLogout=0x7f060006;
        public static final int preferenceLogoutSummary=0x7f060007;
        public static final int preferenceMore=0x7f06007c;
        public static final int preferenceNightMode=0x7f06001f;
        public static final int preferencePaymentMethod=0x7f060067;
        public static final int preferencePaymentMethodSummary=0x7f060068;
        public static final int preferenceScreenRotation=0x7f06001b;
        public static final int preferenceShowHintsOnStartup=0x7f06003f;
        public static final int preferenceSignup=0x7f060008;
        public static final int preferenceSignupSummary=0x7f060009;

        public static final int preferenceTermsConditions=0x7f060028;
        public static final int preferenceTermsConditionsSummary=0x7f060029;
        public static final int preferenceUseSdCard=0x7f06007b;

        public static final int preferenceUserAccount=0x7f060003;
        public static final int preferenceUserAccountLogin=0x7f060004;
        public static final int preferenceUserAccountLoginSummary=0x7f060005;
        public static final int previous=0x7f0600ab;
        public static final int price=0x7f06009b;
        public static final int provided=0x7f06009e;
        public static final int renderingBookinfo=0x7f060024;

        public static final int renderingBookmark=0x7f060020;
        public static final int renderingBookmarkManage=0x7f060023;
        public static final int renderingBookmarkSeeList=0x7f060022;
        public static final int renderingBookmarkThisPage=0x7f060021;

        public static final int renderingFailure=0x7f060070;
        public static final int renderingGoto=0x7f06005e;
        public static final int renderingNavigate=0x7f060062;
        public static final int renderingNextScreen=0x7f06005d;

        public static final int renderingPreviousScreen=0x7f06005c;
        public static final int renderingTableOfContents=0x7f060060;
        public static final int renderingToc=0x7f06005f;
        public static final int sdcard_cache_directory=0x7f0600c3;
        public static final int sdcard_default=0x7f0600c2;
        public static final int search=0x7f060092;
        public static final int searchHint=0x7f060076;
        public static final int server_connection_interval=0x7f0600c1;

        public static final int server_endpoint=0x7f0600bd;
        public static final int title=0x7f060098;
        public static final int username=0x7f060093;
        public static final int verified=0x7f06009f;
        public static final int warning=0x7f0600a9;
        public static final int zipCode=0x7f0600a4;
    }
    public static final class style {
        public static final int SettingsCategory=0x7f080000;
        public static final int SettingsItem=0x7f080001;
    }
    public static final class xml {
        public static final int preferences_appearance=0x7f040000;
        public static final int preferences_drm_activated=0x7f040001;
        public static final int preferences_drm_not_activated=0x7f040002;
        public static final int preferences_more=0x7f040003;
        public static final int preferences_useraccount_authenticated=0x7f040004;
        public static final int preferences_useraccount_authenticated_nologout=0x7f040005;
        public static final int preferences_useraccount_not_authenticated=0x7f040006;
        public static final int searchable=0x7f040007;
    }
    public static final class styleable {

        public static final int[] VerifyablePreference = {
            0x7f010000, 0x7f010001
        };

        public static final int VerifyablePreference_verified = 0;

        public static final int VerifyablePreference_verifiedText = 1;
    };
}
